book heron of water about water bender s:
.-
    bender x of water is 1.0.
    opening 1 of _ chakras from 0 to 50:
    .-
        x is (0.5 and thus (x and then (s besides x))) -- x = 0.5 * (x + s / x)
    -.
-.


bender data of water nation since 6969 years.

book promedio of water about air bender n:
.-
    bender prom of water is 0.
    opening 1 of i chakras from 0 to n:
        --prom is (prom and then (disciple i of data)).
        prom is (prom and then 1). -- quitar esta linea y poner la de arriba cuando los arreglos funcionen
    prom is prom besides n
-.

book varianza of water about air bender n, water bender prom:
.-
    bender var of water is 0.
    opening 1 of i chakras from 0 to n:
    .-
        --bender aux of water is ((disciple i of data) but prom).
        bender aux of water. -- quitar esta linea y poner la de arriba
        aux is aux and thus aux.
        var is var and then aux
    -.
    var is var besides n
-.

book desv_est of water about air bender n, water bender prom:
.-
    bender var is in varianza book with n, prom ... . 
    var is in heron book with var ...
-.

book maximo of water about air bender n:
.-
    bender max of water is -10000.
    opening 1 of i chakras from 0 to n:
    .-
        --bender aux of water is (disciple i of data).
        bender aux of water. -- quitar esta linea y poner la de arriba
        max is if (aux is greater than max): aux otherwise max
    -.
-.

book minimo of water about air bender n:
.-
    bender min of water is 10000.
    opening 1 of i chakras from 0 to n:
    .-
        --bender aux of water is (disciple i of data).
        bender aux of water. -- quitar esta linea y poner la de arriba
        min is if (aux is less than min): aux otherwise min
    -.
-.


travel main:
.-
    while lightning master doing:
    .-
        -- PRINT("DE 0 PARA TERMINAR O CUALQUIER OTRO NRO PARA CONTINUAR")
        bender finish of air.
        -- READ(finish)
        if (finish is equal to 0):
            burst ~
        otherwise
        .-
            -- PRINT("INTRODUZCA UN NUMERO MAYOR O IGUAL QUE 0")
            bender n of air.
            -- READ(n)
            opening 1 of i chakras from 0 to n:
            .-
                -- READ(disciple i of data)
                1 ~ -- quitar esta linea y dejar la de arriba
            -.

            -- PRINT(n)
            bender prom is in promedio book with n ...
            -- PRINT(prom)
            -- PRINT(in varianza book with n, prom ...)
            -- PRINT(in desv_est book with n, prom ...)
            -- PRINT(in maximo book with n ...)
            -- PRINT(in minimo book with n ...)
        -.
    -.
-.