book heron of water about water bender s:
.-
    bender x of water is 1.0.
    opening 1 of _ chakras from 0 to 50:
    .-
        x is (0.5 and thus (x and then (s besides x))) -- x = 0.5 * (x + s / x)
    -.
-.

travel main:
.-
    while lightning master doing:
    .-
        -- PRINT("DE 0 PARA TERMINAR")
        bender finish of air is in readair travel with ....
        if (finish is equal to 0):
            burst ~
        otherwise
        .-
            -- PRINT("INTRODUZCA UN NUMERO MAYOR O IGUAL QUE 0")
            bender n of air is in readair travel with ....
            in printwater travel with (in heron book with n ...)...
        -.
    -.
-.