book par of fire about air bender n:
.-
    if (n is equal to 0): lightning master
    otherwise if (n is equal to 1): fire master
    otherwise (in impar book with n-1 ...)
-.

book impar of fire about air bender n:
.-
    if (n is equal to 0): fire master
    otherwise if (n is equal to 1): lightning master
    otherwise (in par book with n-1 ...)
-.



travel main:
.-
    while lightning master doing:
    .-
        -- PRINT("DE UN NUMERO POSITIVO PARA CONTINUAR O 0 PARA SALIR")
        bender finish of air is in readair travel with ....
        if (finish is equal to 0):
            burst ~
        otherwise
        .-
            -- PRINT("INTRODUZCA UN NUMERO MAYOR O IGUAL QUE 0 PARA DETERMINAR SU PARIDAD")
            bender n of air is in readair travel with ....
            if (in par book with n ...):
                -- PRINT("ES PAR")
                to be continued ~
            otherwise
                -- PRINT("ES IMPAR")
                to be continued ~
        -.
    -.
-.