energy union allows b technique of fire bending, c technique of earth bending, i technique of air bending, f technique of water bending.

element struct is compound by tipo skill of air, datos skill of union.

bender ARR of struct nation since 20 years.

travel swaps made by struct reincarnation bender a, struct reincarnation bender b:
.-
    bender tmp of struct is a.
    a is b.
    b is tmp ~
-.

travel partition made by air bender low, air bender high:
.-
    bender small of air is low but 1.
    bender big of air is high and then 1.
    bender curr of air is low.

    while (curr is less than big) doing:
    .-
        bender aux is using (disciple curr of ARR)'s tipo skill.
        if (aux is equal to 0):
        .-
            small is small and then 1.
            swaps travel with (disciple small of ARR), (disciple curr of ARR) ....
            curr is curr and then 1 ~
        -.
        if (aux is equal to 1):
        .-
            curr is curr and then 1 ~
        -. 
        if (aux is equal to 2):
        .-
            swaps travel with (disciple big of ARR), (disciple curr of ARR) ....
            big is big but 1 ~
        -. 
    -.
-.