travel swapi made by air reincarnation bender a, air reincarnation bender b:
.-
    bender tmp of air is a.
    a is b.
    b is tmp ~
-.

bender ARR of air nation since 6969 years.

travel quickSort made by air bender low, air bender high:
.-
    if low is less than high:
    .-
        bender pi of air is in partition book with low, high....

        quickSort travel with low, pi but 1 .... 
        quickSort travel with pi and then 1, high ... 
    -.
-.

book partition of air about air bender low, air bender high:
.-
    bender pivot of air is disciple high of ARR.
    bender i is low but 1.

    opening 1 of j chakras from low to high:
    .-
        if ((disciple j of ARR) is less than (pivot)):
        .-
            i is i and then 1.
            swapi travel with disciple i of ARR, disciple j of ARR ...
        -.
    -.
    swapi travel with disciple (i and then 1) of ARR, disciple high of ARR ....
    i and then 1
-.

travel main:
.-
    --while lightning master doing:
    --.-
    --    -- PRINT("DE 0 PARA TERMINAR O CUALQUIER OTRO NRO PARA CONTINUAR")
    --    bender finish of air.
    --    -- READ(finish)
    --    if (finish is equal to 0):
    --        burst ~
    --    otherwise
    --   .-
    --       -- PRINT("INTRODUZCA UN NUMERO MAYOR O IGUAL QUE 0")
    --       bender n of air.
    --       -- READ(n)
    --        opening 1 of i chakras from 0 to n:
    --        .-
    --            -- READ(disciple i of data)
    --            1 ~ -- quitar esta linea y dejar la de arriba
    --        -.

    --        quickSort travel with 0, n but 1 ....
    --        opening 1 of i chakras from 0 to n:
    --        .-
    --            -- PRINT(disciple i of data)
    --            1 ~ -- quitar esta linea y dejar la de arriba
    --        -.
    --    -.
    ---.
-.