bender FROM of air nation since 169 years.
bender TO of air nation since 169 years.

bender V of air.
bender E of air.

bender VIS of fire nation since 169 years.

travel dfs made by air bender u:
.-
    disciple u of VIS really is lightning master.
    in printair travel with u....
    in printearth travel with '\n'....
    opening 1 of i chakras from 0 to E:
    .-
        -- a->b
        bender a is disciple i of FROM.
        bender b is disciple i of TO.
        if ((a is equal to u) and ((disciple b of VIS) is equal to fire master)):
        .-
            in dfs travel with b...
        -.
    -.
-.

travel main:
.-
    in printmetal travel with "DE EL NUMERO DE NODOS\n"....
    in readair travel with V....
    in printmetal travel with "DE EL NUMERO DE EDGES\n"....
    in readair travel with E....
    opening 1 of i chakras from 0 to E:
    .-
        in printmetal travel with "DE UN EDGE DIRECCIONAL (DOS ENTEROS, EMPEZANDO DESDE 0)\n"....
        in readair travel with (disciple i of FROM)....
        in readair travel with (disciple i of TO)...
    -.
    opening 1 of u chakras from 0 to V:
    .-
        -- a->b
        if ((disciple u of VIS) is equal to fire master):
        .-
            in dfs travel with u...
        -.
    -.
-.