book it_fib of air about air bender n:
.-
    if (n is equal to 0): 
        this story comes to an end 0~.
    bender dp of air is 0.
    bender next_dp of air is 1.
    opening 1 of _ chakras from 0 to n:
    .-
        next_dp is dp and then next_dp. -- f(n+1) = f(n-1) + f(n)
        dp is next_dp but dp            -- f(n) = f(n+1) - f(n-1)
    -.
-.

travel main:
.-
    while lightning master doing:
    .-
        in printmetal travel with "DE 0 PARA TERMINAR O 1 PARA FIB ITER\n"....
        bender finish of air.
        in readair travel with finish....
        if (finish is equal to 0):
            burst ~
        otherwise
        .-
            in printmetal travel with "INTRODUZCA UN NUMERO MAYOR O IGUAL QUE 0\n"....
            bender n of air.
            in readair travel with n....
            in printair travel with (in it_fib book with n ...)....
            in printearth travel with '\n'...
        -.
    -.
-.