book heron of water about water bender s:
.-
    bender x of water is 1.0.
    opening 1 of _ chakras from 0 to 50:
    .-
        x is (0.5 and thus (x and then (s besides x))) -- x = 0.5 * (x + s / x)
    -.
-.

travel main:
.-
    while lightning master doing:
    .-
        in printmetal travel with "DE 0 PARA TERMINAR O 1 PARA CONTINUAR\n"....
        bender finish of air.
        in readair travel with finish....
        if (finish is equal to 0):
            burst ~
        otherwise
        .-
            in printmetal travel with "INTRODUZCA UN NUMERO REAL MAYOR O IGUAL QUE 0\n"....
            bender n of water.
            in readwater travel with n....
            in printwater travel with (in heron book with n ...)....
            in printearth travel with '\n'...
        -.
    -.
-.