element pto is compound by x skill of air, y skill of air.
energy union allows x technique of air bending, y technique of air bending.

travel fun made by air reincarnation bender a, air reincarnation bender b:
.-
    in readair travel with (a)....
    in readair travel with (b)....
-.


travel main:
.-
    bender p1 of pto.
    bender p2 of union.
    p2 is learning union's y technique from 69.
    in fun travel with (using p1's x skill), (using p2's y technique)....
    in printair travel with (using p1's x skill)....
    in printair travel with (using p1's y skill)....
    in printair travel with (using p2's y technique)....
-.