energy union allows b technique of fire bending, c technique of earth bending, i technique of air bending, f technique of water bending.

element struct is compound by tipo skill of air, datos skill of union.

bender ARR of struct nation since 20 years.

travel swaps made by struct reincarnation bender a, struct reincarnation bender b:
.-
    bender tmp of struct is a.
    a is b.
    b is tmp ~
-.

travel partition made by air bender low, air bender high:
.-
    bender small of air is low but 1.
    bender big of air is high and then 1.
    bender curr of air is low.

    while (curr is less than big) doing:
    .-
        bender aux is using (disciple curr of ARR)'s tipo skill.
        if (aux is equal to 0):
        .-
            small is small and then 1.
            swaps travel with (disciple small of ARR), (disciple curr of ARR) ....
            curr is curr and then 1 ~
        -.
        if (aux is equal to 1):
        .-
            curr is curr and then 1 ~
        -. 
        if (aux is equal to 2):
        .-
            big is big but 1.
            swaps travel with (disciple big of ARR), (disciple curr of ARR) ....
        -. 
    -.
-.

travel main:
.-
    in printmetal travel with "DIGA CUANTOS ELEMENTOS A ORDENAR\n"....
    bender n of air.
    in readair travel with n....
    opening 1 of j chakras from 0 to n:
    .-
        in printearth travel with '\n'....
        in readair travel with (using (disciple j of ARR)'s tipo skill)....
        if ((using (disciple j of ARR)'s tipo skill) is equal to 0):
        .-
            bender tmp of fire.
            in readfire travel with tmp....
            (disciple j of ARR)'s datos is (learning union's b technique from tmp)~
        -.
        otherwise if ((using (disciple j of ARR)'s tipo skill) is equal to 1):
        .-
            bender tmp of earth.
            in readearth travel with tmp....
            (disciple j of ARR)'s datos is (learning union's c technique from tmp)~
        -.
        otherwise
        .-
            bender tmp of air.
            in readair travel with tmp....
            (disciple j of ARR)'s datos is (learning union's i technique from tmp)~
        -.
    -.
    in partition travel with 0, n but 1....
    opening 1 of j chakras from 0 to n:
    .-
        if ((using (disciple j of ARR)'s tipo skill) is equal to 0):
        .-
            in printfire travel with (using (using (disciple j of ARR)'s datos skill )'s b technique )....
        -.
        otherwise if ((using (disciple j of ARR)'s tipo skill) is equal to 1):
        .-
            in printearth travel with (using (using (disciple j of ARR)'s datos skill )'s c technique )....
        -.
        otherwise
        .-
            in printair travel with (using (using (disciple j of ARR)'s datos skill )'s i technique )....
        -.
        in printearth travel with '\n'...
    -.
-.