travel swapi made by air reincarnation bender a, air reincarnation bender b:
.-
    bender tmp of air is a.
    a is b.
    b is tmp ~
-.


travel quickSort made by air bender low, air bender high, air nation bender ARR:
.- 
    if low is less than high:
    .-
        bender pi of air is in partition book with low, high, ARR....

        quickSort travel with low, pi but 1, ARR .... 
        quickSort travel with pi and then 1, high, ARR ... 
    -.
-.

book partition of air about air bender low, air bender high, air nation bender ARR:
.-
    bender pivot of air is disciple high of ARR.
    bender i is low but 1.

    opening 1 of j chakras from low to high:
    .-
        if ((disciple j of ARR) is less than (pivot)):
        .-
            i is i and then 1.
            swapi travel with disciple i of ARR, disciple j of ARR ...
        -.
    -.
    swapi travel with disciple (i and then 1) of ARR, disciple high of ARR ....
    i and then 1
-.

travel main:
.-
    bender ARR of air nation since 50 years.
    while lightning master doing:
    .-
        in printmetal travel with "DE 0 PARA TERMINAR O 1 CONTINUAR"....
        bender finish of air.
        in readair travel with finish....
        if (finish is equal to 0):
            burst ~
        otherwise
        .-
            in printmetal travel with "INTRODUZCA LA CANTIDAD DE ENTEROS"....
            bender n of air.
            in readair travel with n....
            opening 1 of i chakras from 1 to (n and then 1):
            .-
                in readair travel with (disciple i of ARR)....
            -.
            in quickSort travel with 1, n, ARR....
            opening 1 of i chakras from 1 to (n and then 1):
            .-
                in printair travel with (disciple i of ARR)....
            -.
        -.
    -.
-.