travel main:
.-
    bender ARR of air nation since 6969 years.
    while lightning master doing:
    .-
        in printmetal travel with "DE 0 PARA TERMINAR O 1 CONTINUAR"....
        bender finish of air.
        in readair travel with finish....
        if (finish is equal to 0):
            burst ~
        otherwise
        .-
            in printmetal travel with "INTRODUZCA LA CANTIDAD DE ENTEROS"....
            bender n of air.
            in readair travel with n....
            opening 1 of i chakras from 0 to n:
            .-
                in readair travel with (disciple i of ARR)....
            -.
            opening 1 of i chakras from 0 to n:
            .-
                in printair travel with (disciple i of ARR)....
            -.
        -.
    -.
-.