

bender globalArray of air nation is master of 1, 2, 3 right now.

book f of air:
.-
	-- in g travel with globalArray ....
	-- bender localArray of air nation since 5.9 years.
	-- localArray is master of 1,2,3,4 right now.
	-- bender arrB of air nation since 6 years is master of 1,2,3 right now.
	-- localArray is arrB.
	disciple 0 of globalArray really is 42.

	disciple 0 of globalArray 
-.


travel g made by air nation bender arrParam:
.-
	bender x is disciple 0 of arrParam.
	0 ~
-.